apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: register-team
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - matrix:
      generators:
      - clusters:
          selector:
            matchLabels:
              cluster-role: hub
      - git:
          repoURL: '{{ .metadata.annotations.platform_url }}'
          revision: HEAD
          directories:
          - path: team/*
  template:
    metadata:
      name: '{{ .path.basename }}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: '{{ .metadata.annotations.platform_url }}'
        path: charts/register-team
        targetRevision: HEAD
        helm:
          valueFiles:
          - '../../team/{{ .path.basename }}/environments.yaml'
          parameters:
          - name: teamName
            value: '{{ .path.basename }}'
      destination:
        server: '{{ .server }}'
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
