version: 0.2
phases:
  pre_build:
    commands:
      - |
        yum install -y gettext
        # Helm installation
        curl --silent --location "https://get.helm.sh/helm-v3.9.2-linux-amd64.tar.gz" | tar xz -C /tmp
        mv /tmp/linux-amd64/helm /usr/local/bin
        chmod +x /usr/local/bin/helm
        # Terraform installation
        sudo yum install -y yum-utils
        sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
        sudo yum -y install terraform

  build:
    commands:
      - |
        set -x
        set -e

        aws configure set cli_pager ""

        ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
        BUCKET_NAME=${TFSTATE_BUCKET_NAME}
        BASE_DIR=${CODEBUILD_SRC_DIR}
        WORKSHOP_GIT_URL=${WORKSHOP_GIT_URL:-https://github.com/aws-samples/eks-blueprints-for-terraform-workshop}
        WORKSHOP_GIT_BRANCH=${WORKSHOP_GIT_BRANCH:-mainline}
        WORKSHOP_GIT_TAG=${WORKSHOP_GIT_TAG:-v1.0.0}
        env | sort

        # clone and create CodeCommit repo
        git clone $WORKSHOP_GIT_URL $BASE_DIR || true
        cd $BASE_DIR
        git checkout $WORKSHOP_GIT_TAG
        cd -

        # This gives access to the EKS cluster in terraform

        # Spokes backend config
        cat << EOT > $BASE_DIR/terraform/spoke/backend_override.tf
        terraform {
          backend "s3" {
            bucket         = "$BUCKET_NAME"
            key            = "spoke/terraform.tfstate"
            region         = "$AWS_REGION"
          }
        }
        EOT

        mkdir -p ~/.ssh

        if [[ $REQUESTED_ACTION == 'Delete' ]]; then
          # Cleanup scripts
          DEBUG=1 $BASE_DIR/terraform/spoke/destroy.sh 
        else
          # Project Creation
          DEBUG=1 $BASE_DIR/terraform/spoke/deploy.sh 
        fi
  post_build:
    commands:
      # CODEBUILD_BUILD_SUCCEEDING = 1 Set to 0 if the build is failing, or 1 if the build is succeeding.
      - echo ">>> build status $CODEBUILD_BUILD_SUCCEEDING "
